# Generated by Django 3.2.13 on 2022-06-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newslettre',
            new_name='Newsletter',
        ),
    ]
