# Generated by Django 3.2.13 on 2022-06-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
    ]
