# Generated by Django 3.2.13 on 2022-05-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_categories_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'order_date', 'ordering': ['-published_date']},
        ),
    ]
