# Generated by Django 3.2.13 on 2022-05-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220529_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/empty.jpg', upload_to='category/'),
        ),
    ]
